### ISSUE TITLE
Crawl functionality

### ISSUE THREAD

**Issue by anotherdevs** [rverton/webanalyze#15]
Hi @rverton 

Is it possible to add a crawl functionality that crawls fx. the first 20 (configurable) found sub pages?

Wappalyzer has these variables available:
maxDepth
maxUrls
maxWait
recursive

**Comment by rverton** [comment]
I think this can be added easy. Will think over this and let you know.

**Comment by rverton** [comment]
This was a bit more work than I thought. I added a waitgroup for the job channel so I can feed the new URLs to the worker queue. Additionally, comparing URLs can be a bit tricky.
There is no depth setting currently and it is only crawling from the initial page load for now. Let me know if this works for you.
