### ISSUE TITLE
Several errors - running parrot linux

### ISSUE THREAD

**Issue by Shiva108** [rverton/webanalyze#17]
./webanalyze.go -h
./webanalyze.go: line 1: package: command not found
./webanalyze.go: line 3: syntax error near unexpected token `newline'
./webanalyze.go: line 3: `import ('

**Comment by rverton** [comment]
Hi @Shiva108,
you need to have [go installed](https://golang.org/doc/install) to use webanalyze. After this, you can follow the Usage instructions in the README.

Greetings
