### ISSUE TITLE
Unable to save output results.

### ISSUE THREAD

**Issue by vishu10x00** [rverton/webanalyze#22]
webanalyze -hosts domains > stack

Do you have a way to save results??

**Comment by rverton** [comment]
Hi @vishu10x00,
as described in the README, you can use the `-output` flag to specify the output format. By using a bash redirection you can then save this to a file.

```
webanalyze -host https://stackshare.io -output csv > results.csv
```

Does this answer your question?

**Comment by vishu10x00** [comment]
Thanks :)
