### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by lochv** [rverton/webanalyze#24]
Hi friend, 
I were use webanalyze in my web crawler, it seem memory leak in process func but i canot resolve it, can u help me 

![image](https://user-images.githubusercontent.com/17930973/73708069-e50b9d00-472f-11ea-89b2-2b6b56d9a2f1.png)

memory graph captured with pprof

**Comment by rverton** [comment]
Hi @lochv,
can you show me some code how you have intregrated webanalyze in your project? It would also be nice to see a bit more of the pprof.

Thanks

**Comment by lochv** [comment]
hi @rverton,
thx, i just resolved that problem, restrict to create new val
