### ISSUE TITLE
Redirects are followed to other domains with no notification or options

### ISSUE THREAD

**Issue by fuzzerk** [rverton/webanalyze#26]
First,   A W E S O M E   T O O L !

Thank you a billion. 

Problem: 
When analyzing a subdomain that immediately redirects to a completely different subdomain, the tool analyzes the destination domain. There is no notification of this in the output, and there is no option to prohibit this behavior. When performing recon inside a scope, this behavior is problematic. 

Solution: 
Flag to ignore redirects and quit. And/or provide notification in the output that the results are for the technologies of a domain other than the one supplied.

**Comment by rverton** [comment]
Hi,
thanks for the issue and sorry for the late response, I just came back from vacation. This should be fixed quickly, will do this in the upcoming days.

**Comment by rverton** [comment]
This is fixed in e17a78973557d17c890ca6b1927e6fe3a0d63fae now. I did not add a flag to ignore this for now because following redirects in this scenario is nearly never what you want.

If there is any demand for this, I'm open for PR.
