### ISSUE TITLE
`fetchHost` doesn't follow redirects

### ISSUE THREAD

**Issue by pshevtsov** [rverton/webanalyze#35]
I'm wondering about the decision of not following redirects with `http.Client` within `fetchHost` function: https://github.com/rverton/webanalyze/blob/master/webanalyze.go#L105

Following HTTP redirects is crucial for our use case.

What do you think about adding the ability to provide some custom `http.Client` to `NewWebAnalyzer`?

I'm going to submit a pull request to better describe the idea.

**Comment by rverton** [comment]
Hi @pshevtsov,
following redirects often led to leaving the target scope/environment.

I'm open to make this more configurable if you need it.

Greetings

**Comment by pshevtsov** [comment]
@rverton PTAL #37
