### ISSUE TITLE
-silent option doesn't filter the -update output status

### ISSUE THREAD

**Issue by superhac** [rverton/webanalyze#52]
When executing the following the "-silent" option is still providing the "-update" header in the output:

`./webanalyze -apps technologies.json -update -silent -output json -host 10.10.10.238`  

The Output:

`2021/07/01 20:43:09 app definition file updated from  https://raw.githubusercontent.com/AliasIO/Wappalyzer/master/src/technologies.json
{"hostname":"http://10.10.10.238","matches":[{"app":{"cats":["22"],"category_names":["Web servers"],"cookies":null,"headers":{"Server":"(?:Apache(?:$|/([\\d.]+)|[^/-])|(?:^|\\b)HTTPD)\\;version:\\1"},"meta":null,"html":null,"script":null,"url":null,"website":"http://apache.org","implies":null},"app_name":"Apache","matches":[["Apache/2.4.29","2.4.29"]],"version":"2.4.29"},{"app":{"cats":["28"],"category_names":["Operating systems"],"cookies":null,"headers":{"Server":"Ubuntu","X-Powered-By":"Ubuntu"},"meta":null,"html":null,"script":null,"url":null,"website":"http://www.ubuntu.com/server","implies":null},"app_name":"Ubuntu","matches":[["Ubuntu"]],"version":""}]}`

Notice how the first line, "2021/07/01 20:43:09 app definition file updated from  https://raw.githubusercontent.com/AliasIO/Wappalyzer/master/src/technologies.json" is still being included in the output.  

Can we get that silenced too?

BTW - Great app!

**Comment by bugbaba** [comment]
Hey @superhac,

I have just created a pull request to fix this, Please give it a try. Before it gets merged :)

--
Regards,
@bugbaba

**Comment by superhac** [comment]
It works!  Thank you very much @bugbaba!
