### ISSUE TITLE
Not all rules are processed due to inconsistent field type

### ISSUE THREAD

**Issue by CaledoniaProject** [rverton/webanalyze#60]
According to the documents and issue here 

* https://github.com/AliasIO/wappalyzer/blob/master/README.md
* https://github.com/AliasIO/wappalyzer/issues/4879

Fields like `scriptSrc`, `html` and many others are not always in string form, it could be a map or an array of string. 

Looks like webanalyze process string type only, can you fix it?

**Comment by rverton** [comment]
I do have implemented a 'string/[]string' type here which handles most of this cases: https://github.com/rverton/webanalyze/blob/master/wappalyze.go#L16

I think the bigger problem currently is the modified schema. I opened an issue at #57.
