### ISSUE TITLE
Anyway to store the results in json or csv format? 

### ISSUE THREAD

**Issue by salooali** [rverton/webanalyze#61]
Thanks for this tool..!

I'm just having a porbelm in storing the results in a json or csv format.

**Comment by rverton** [comment]
So what problem are you referring to? You need to describe whats not working for you, otherwise I cant help.

**Comment by salooali** [comment]
I've a huge list of domains and i want to detect what CMS or technologies they are using for this purpose i want to store the result for each domain in json or csv format but i didn't find any way to store the results

**Comment by rverton** [comment]
As you can see in the `README.md` (and via the `-h` flag), there is an option `-output`:
```
$ ./webanalyze -h
Usage of ./webanalyze:
  -apps string
        app definition file. (default "apps.json")
  -crawl int
        links to follow from the root page (default 0)
  -host string
        single host to test
  -hosts string
        filename with hosts, one host per line.
  -output string     <----------------------------------
        output format (stdout|csv|json) (default "stdout")
  -search
        searches all urls with same base domain (i.e. example.com and sub.example.com) (default true)
  -silent
        avoid printing header (default false)
  -update
        update apps file
  -worker int
        number of worker (default 4)
```

**Comment by salooali** [comment]
Hey ofcourse  I've tried this but this is not working for me i'm using the
following command:
webanalyze -host https://partakefoods.com/ -output csv
It will only print the result in csv format on the terminal not on the
separate file.I hope you get it.

**Comment by rverton** [comment]
You can redirect the output to a file then via your shell, for example:
`webanalyze -host google.com -output csv > result.csv`

**Comment by salooali** [comment]
Ofcourse i can do this. But as i told you before I've a huge list of
domains.
There should be a way of storing the output in a file with respective
domain in csv or json format.

**Comment by rverton** [comment]
I don't understand what the problem is with redirecting it into a file. It does not matter how huge your list is, this will work.

**Comment by salooali** [comment]
It means If I've 10k websites than I've to create 10k individual files. Is
this approach good to you? What if we store all the results in a single
file in json format like
Domain: {technologies}

**Comment by rverton** [comment]
You can load a list of domains to check and put all results in a single file:
`webanalyze -hosts fileWithUrls.txt -output csv > fileWithResults.txt`

Please have a look at the help output. I'm locking this issue now.
