### ISSUE TITLE
'Unexpected EOF' Error When Compiling

### ISSUE THREAD

**Issue by edwinfred** [rverton/webanalyze#62]
When installing the tool using `go install github.com/rverton/webanalyze/cmd/webanalyze@latest`, it's throwing the error,
```
/home/michael/go/pkg/mod/golang.org/x/net@v0.0.0-20200202094626-16171245cfb2/idna/idna10.0.0.go:25:2: golang.org/x/text@v0.3.0: unexpected EOF
```

**Comment by rverton** [comment]
I think this is a problem on your site. Did you recently update Go? Try clearing the pkg folder so all modules are re-downloaded.
