### ISSUE TITLE
Piping of exact output to external tools / scripts

### ISSUE THREAD

**Issue by TheeEclipse** [rverton/webanalyze#75]
The [webanalyze](https://github.com/rverton/webanalyze) doesnt allow Piping of exact output to external tools / scripts .
``` 
root@Automations:~# /root/go/bin/webanalyze  -silent -redirect -host sitehere.com | anew 2.txt
http://sitehere.com error: Failed to retrieve: Get "http://sitehere.com": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
```
But my fork does:
https://github.com/TheeEclipse/webanalyze

I opened the pull request

**Comment by rverton** [comment]
As mentioned in the PR, I will close this for now because I'm fine with the stdout method for now. If you need to pipe, please use CSV/JSON in combination with `cut` or `jq`.
