### ISSUE TITLE
not ussing https:// to grep tech

### ISSUE THREAD

**Issue by sushantdhopat** [rverton/webanalyze#77]
whenever I am passed a list of subdomains to scan tech

```
google.com
cisco.com
bing.com
doepichack.com
etc
```

this is passing like only 
```
http://bing.com
http://cisco.com
etc
```
so some domains are showing results on http://, and some are not so why is this happening

**Comment by rverton** [comment]
If no scheme is provided, `http` is used. If you want to enforce HTTPS, you can prepend the scheme in your list:
```
https://google.com
https://foo.com
```
